import io
import re
from typing import Dict, Any, Optional
from PIL import Image, ExifTags

SMARTPHONE_BRANDS = [
    "apple", "iphone", "samsung", "xiaomi", "redmi", "poco", "oppo", "vivo",
    "realme", "google", "pixel", "oneplus", "huawei", "honor", "motorola",
    "moto", "asus zenfone", "asus rog", "infinix", "tecno", "sony xperia",
    "nokia", "zte", "lg"
]

DEDICATED_CAMERAS = [
    "canon", "nikon", "sony", "fujifilm", "fuji", "panasonic", "lumix",
    "leica", "olympus", "om digital", "om system", "hasselblad", "pentax",
    "ricoh", "phase one", "sigma", "blackmagic"
]

WEBCAM_LAPTOP_BRANDS = [
    "webcam", "integrated camera", "hd webcam", "facetime hd", "usb camera",
    "logitech", "brio", "streamcam", "c920", "c922", "c930", "c270", "c310",
    "razer kiyo", "elgato facecam", "avermedia", "creative live", "obsbot",
    "chicony", "sunplus", "realtek", "bisoncam", "lenovo easycamera",
    "dell webcam", "hp wide vision", "hp truevision", "asus uvc",
    "surface camera", "windows camera"
]

AI_SIGNATURES = [
    # OpenAI / ChatGPT / DALL-E
    "dall-e", "dall·e", "dalle", "chatgpt", "openai",
    # Google Gemini & Imagen
    "gemini", "imagen", "google imagen", "synthid",
    # Microsoft & Copilot
    "copilot", "bing image creator", "designer.microsoft",
    # Midjourney, Stable Diffusion & FLUX
    "midjourney", "stable diffusion", "sdxl", "comfyui", "automatic1111",
    "novelai", "invokeai", "fooocus", "c2pa", "contentcredentials",
    "flux.1", "flux", "black forest labs",
    # Platform Populer Lainnya
    "adobe firefly", "firefly", "ideogram", "leonardo.ai", "leonardo ai",
    "recraft", "grok", "meta ai", "kandinsky", "deepfloyd",
    "synthetic", "generated by ai", "ai generated"
]

# Signature resmi dan tanda pengenal ekspor Canva
CANVA_SIGNATURES = [
    "canva", "canva.com", "canva design", "canva-design", "canva sans",
    "created with canva", "canva_design", "canva editorial", "canvapro"
]

# Perangkat keras scanner, printer multifungsi, dan mesin fotokopi
SCANNER_PRINTER_BRANDS = [
    "epson", "canoscan", "pixma", "scansnap", "fujitsu", "brother",
    "scanjet", "deskjet", "laserjet", "officejet", "xerox", "kyocera",
    "ricoh", "konica minolta", "plustek", "avision", "mustek",
    "pantum", "lexmark", "sharp", "toshiba", "docucentre",
    "scanner", "flatbed scanner", "document scanner", "mfp", "aio"
]

# Software pengambil dokumen scan & driver TWAIN/WIA
SCANNER_SOFTWARE = [
    "epson scan", "epson scan 2", "epson smart panel", "hp smart",
    "hp scan", "hp scanning", "hp scan and capture", "canon quick menu",
    "canon ij scan utility", "canon scangear", "brother iprint&scan",
    "brother controlcenter", "scansnap home", "scansnap manager",
    "vuescan", "silverfast", "naps2", "not another pdf scanner",
    "windows fax and scan", "windows scan", "paperless", "paperscan",
    "adobe acrobat scan", "simple scan", "xsane", "wia-", "twain"
]

# Dimensi baku kertas hasil scan (A4 / Letter / F4 pada 150, 200, 300, 600 DPI)
SCANNER_STANDARD_RESOLUTIONS = {
    # A4 (210 x 297 mm)
    (2480, 3508): "Dokumen A4 Pindai (300 DPI)",
    (3508, 2480): "Dokumen A4 Landscape (300 DPI)",
    (2479, 3508): "Dokumen A4 Pindai (300 DPI)",
    (3508, 2479): "Dokumen A4 Landscape (300 DPI)",
    (2480, 3507): "Dokumen A4 Pindai (300 DPI)",
    (1654, 2339): "Dokumen A4 Pindai (200 DPI)",
    (2339, 1654): "Dokumen A4 Landscape (200 DPI)",
    (1240, 1754): "Dokumen A4 Pindai (150 DPI)",
    (1754, 1240): "Dokumen A4 Landscape (150 DPI)",
    (4960, 7016): "Dokumen A4 Pindai HD (600 DPI)",
    (7016, 4960): "Dokumen A4 Landscape HD (600 DPI)",
    # US Letter (8.5 x 11 in)
    (2550, 3300): "Dokumen Letter Pindai (300 DPI)",
    (3300, 2550): "Dokumen Letter Landscape (300 DPI)",
    (1700, 2200): "Dokumen Letter Pindai (200 DPI)",
    (1275, 1650): "Dokumen Letter Pindai (150 DPI)",
    # F4 / Folio (215 x 330 mm)
    (2539, 3898): "Dokumen F4 / Folio Pindai (300 DPI)",
    (3898, 2539): "Dokumen F4 / Folio Landscape (300 DPI)"
}

# Template kanvas populer dan resolusi standar Canva

# Template kanvas populer dan resolusi standar Canva
CANVA_CANVAS_PRESETS = {
    (1080, 1080): "Postingan Instagram Persegi (1:1)",
    (1024, 1024): "Postingan Persegi Web (1:1)",
    (1080, 1350): "Postingan Instagram Potret (4:5)",
    (1080, 1920): "Instagram Story / Reels / TikTok (9:16)",
    (1920, 1080): "Presentasi 16:9 / Spanduk Layar Penuh",
    (1280, 720): "Thumbnail YouTube / Header Video",
    (1200, 630): "Postingan Facebook / Banner Tautan",
    (940, 788): "Grafis Facebook Standar",
    (2000, 1000): "Header Twitter / Spanduk Acara",
    (1587, 2245): "Poster A4 Canva (21 x 29.7 cm)",
    (2480, 3508): "Brosur / Dokumen Cetak A4 Canva (300 DPI)",
    (1414, 2000): "Poster Vertikal Standar Canva",
    (500, 500): "Logo / Ikon Persegi Canva",
    (800, 800): "Logo Media Sosial Canva",
    (735, 1102): "Pin Pinterest Canva"
}

# Software yang diketahui menghasilkan screenshot
SCREENSHOT_SOFTWARE = [
    "snipping tool", "snip & sketch", "snagit", "greenshot", "lightshot",
    "sharex", "gyazo", "flameshot", "screenshot", "screencapture",
    "obs studio", "bandicam", "fraps", "xsplit", "nvidia shadowplay",
    "windows screenshot", "print screen", "prtscn", "grab",
    "mac os x", "macos screenshot", "spectacle", "kazam",
    "screenpresso", "picpick", "faststone capture", "hypersnap"
]

# Resolusi layar yang paling umum dipakai (tepat persis piksel)
COMMON_SCREEN_RESOLUTIONS = [
    # HD/FHD Desktop & Laptop
    (1920, 1080), (1080, 1920),
    (2560, 1440), (1440, 2560),
    (3840, 2160), (2160, 3840),  # 4K UHD
    (1366, 768),  (768,  1366),
    (1280, 800),  (800,  1280),
    (1280, 1024), (1024, 1280),
    (1600, 900),  (900,  1600),
    (1440, 900),  (900,  1440),
    (1920, 1200), (1200, 1920),
    (2560, 1600), (1600, 2560),
    # MacBook / Retina
    (2560, 1664), (1664, 2560),
    (2880, 1800), (1800, 2880),
    (3024, 1964), (1964, 3024),
    (2048, 1536), (1536, 2048),
    # Ultrawide
    (3440, 1440), (1440, 3440),
    (2560, 1080), (1080, 2560),
    (5120, 1440), (1440, 5120),
    # Common Mobile Screenshots (landscape/portrait)
    (2532, 1170), (1170, 2532),  # iPhone 12/13 Pro
    (2778, 1284), (1284, 2778),  # iPhone 12/13 Pro Max
    (2340, 1080), (1080, 2340),  # Android Full HD+
    (2400, 1080), (1080, 2400),
    (2460, 1080), (1080, 2460),
    (2560, 1440), (1440, 2560),  # WQHD Mobile
    (3200, 1440), (1440, 3200),  # Samsung S21+
]

def analyze_metadata(image_bytes: bytes, pil_img: Image.Image, filename: str = "") -> Dict[str, Any]:
    """
    Ekstraksi dan analisis metadata EXIF, PNG chunks, dan raw signatures
    untuk mendeteksi apakah gambar berasal dari HP, Kamera Dedicated, atau AI.
    """
    findings = []
    exif_data = {}
    ai_raw_matches = []
    is_canva_signature = False
    
    # 1. Analisis Raw Bytes untuk AI signature, C2PA, dan Canva
    try:
        # Cek potongan awal dan akhir file (chunk header dan trailer)
        raw_head = image_bytes[:100000]
        raw_tail = image_bytes[-100000:] if len(image_bytes) > 100000 else b""
        combined_raw = (raw_head + raw_tail).lower()
        
        for sig in AI_SIGNATURES:
            if sig.encode("utf-8") in combined_raw:
                ai_raw_matches.append(sig)
                findings.append(f"Ditemukan jejak digital signature AI: '{sig}' pada berkas.")

        for cs in CANVA_SIGNATURES:
            if cs.encode("utf-8") in combined_raw:
                is_canva_signature = True
                findings.append(f"Ditemukan jejak digital resmi ekspor platform Canva: '{cs}'.")
                
        # Cek parameter Stable Diffusion khas
        if b"steps:" in combined_raw and b"sampler:" in combined_raw and b"cfg scale:" in combined_raw:
            ai_raw_matches.append("stable_diffusion_prompt_params")
            findings.append("Ditemukan parameter generasi AI Stable Diffusion (Steps, Sampler, CFG scale).")
    except Exception as e:
        pass

    # 2. Analisis PNG Info & Metadata Comment
    png_info = {}
    if hasattr(pil_img, "info") and pil_img.info:
        for k, v in pil_img.info.items():
            if isinstance(v, str):
                png_info[k] = v[:200]
                lower_v = v.lower()
                for sig in AI_SIGNATURES:
                    if sig in lower_v:
                        ai_raw_matches.append(f"png_{k}_{sig}")
                        findings.append(f"Header metadata '{k}' mencatat data AI ({sig}).")
                for cs in CANVA_SIGNATURES:
                    if cs in lower_v:
                        is_canva_signature = True
                        findings.append(f"Header metadata '{k}' mencatat data Canva ({cs}).")

    # 3. Analisis EXIF
    has_exif = False
    make = ""
    model = ""
    lens_model = ""
    software = ""
    focal_length = None
    focal_length_35mm = None
    iso = None
    f_number = None
    exposure_time = None
    date_time = None

    try:
        raw_exif = pil_img.getexif()
        if raw_exif:
            has_exif = True
            for tag_id, value in raw_exif.items():
                tag_name = ExifTags.TAGS.get(tag_id, str(tag_id))
                exif_data[tag_name] = str(value)
                
            # Cek IFD Exif tambahan
            for ifd_id in (ExifTags.IFD.Exif, ExifTags.IFD.GPSInfo):
                try:
                    ifd = raw_exif.get_ifd(ifd_id)
                    for k, v in ifd.items():
                        tag_name = ExifTags.TAGS.get(k, str(k))
                        exif_data[tag_name] = str(v)
                except Exception:
                    pass

            make = str(exif_data.get("Make", "")).strip()
            model = str(exif_data.get("Model", "")).strip()
            lens_model = str(exif_data.get("LensModel", "")).strip()
            software = str(exif_data.get("Software", "")).strip()
            date_time = str(exif_data.get("DateTimeOriginal", exif_data.get("DateTime", ""))).strip()
            
            # Numeric fields
            try:
                if "FocalLength" in exif_data:
                    focal_length = float(exif_data["FocalLength"])
            except Exception:
                pass
            try:
                if "FocalLengthIn35mmFilm" in exif_data:
                    focal_length_35mm = float(exif_data["FocalLengthIn35mmFilm"])
            except Exception:
                pass
            try:
                if "ISOSpeedRatings" in exif_data:
                    iso = int(exif_data["ISOSpeedRatings"])
                elif "PhotographicSensitivity" in exif_data:
                    iso = int(exif_data["PhotographicSensitivity"])
            except Exception:
                pass
            try:
                if "FNumber" in exif_data:
                    f_number = float(exif_data["FNumber"])
            except Exception:
                pass
            try:
                if "ExposureTime" in exif_data:
                    exposure_time = str(exif_data["ExposureTime"])
            except Exception:
                pass

    except Exception as e:
        pass

    # 3.1 Ekstraksi DPI Resolusi Cetak/Pindai
    dpi_val = None
    if hasattr(pil_img, "info") and pil_img.info and "dpi" in pil_img.info:
        dpi_info = pil_img.info["dpi"]
        if isinstance(dpi_info, (tuple, list)) and len(dpi_info) >= 2:
            try:
                dpi_val = int(round(float(dpi_info[0])))
            except Exception:
                pass
    
    if not dpi_val and "XResolution" in exif_data:
        try:
            x_res_str = str(exif_data["XResolution"])
            if "/" in x_res_str:
                num, den = x_res_str.split("/")
                dpi_val = int(round(float(num) / float(den)))
            else:
                dpi_val = int(round(float(x_res_str)))
        except Exception:
            pass

    # 4. Evaluasi Tipe Perangkat dari Metadata
    device_category = "unknown"
    make_lower = make.lower()
    model_lower = model.lower()
    software_lower = software.lower()
    full_cam_str = f"{make_lower} {model_lower} {software_lower}".strip()
    img_wh = (pil_img.width, pil_img.height)

    # --- Deteksi Scanner & Printer Multifungsi ---
    is_scanner_brand = any(sb in full_cam_str for sb in SCANNER_PRINTER_BRANDS)
    is_scanner_software = any(ss in software_lower for ss in SCANNER_SOFTWARE)
    is_scanner_filename = any(k in filename.lower() for k in ["scan", "scanned", "skan", "img_scan", "scan_", "dokumen_"])
    
    # Deteksi resolusi dokumen kertas baku scanner
    scan_preset = SCANNER_STANDARD_RESOLUTIONS.get(img_wh)
    if not scan_preset:
        scan_preset = SCANNER_STANDARD_RESOLUTIONS.get((pil_img.height, pil_img.width))

    is_scanner = (
        is_scanner_brand or 
        is_scanner_software or 
        (scan_preset and dpi_val in [150, 200, 300, 400, 600] and not lens_model and not focal_length) or
        (is_scanner_filename and (scan_preset or dpi_val in [150, 200, 300, 600]) and not has_exif)
    )

    # --- Deteksi Screenshot via Software Metadata ---
    is_screenshot_software = any(s in software_lower for s in SCREENSHOT_SOFTWARE)
    # Deteksi via nama file
    is_screenshot_filename = any(k in filename.lower() for k in [
        "screenshot", "screen_capture", "capture", "snap", "screenrecord",
        "snip", "scr_", "screenshot_"
    ])
    # Deteksi via resolusi layar tepat
    is_screen_resolution = img_wh in COMMON_SCREEN_RESOLUTIONS

    is_webcam = any(b in full_cam_str for b in WEBCAM_LAPTOP_BRANDS)
    is_phone = any(b in full_cam_str for b in SMARTPHONE_BRANDS)
    is_camera = any(b in full_cam_str for b in DEDICATED_CAMERAS)

    is_canva_software = any(cs in software_lower for cs in CANVA_SIGNATURES)
    is_canva_filename = any(cs in filename.lower() for cs in ["canva", "desain tanpa judul", "untitled design"])
    
    # Deteksi template kanvas standar Canva
    canva_preset = CANVA_CANVAS_PRESETS.get(img_wh)
    if not canva_preset:
        canva_preset = CANVA_CANVAS_PRESETS.get((pil_img.height, pil_img.width))
        
    is_canva_likely = bool(is_canva_signature or is_canva_software or is_canva_filename or (canva_preset and not has_exif))

    if is_scanner:
        device_category = "scanner"
        findings.append(f"Terdeteksi perangkat scanner dokumen / scan printer: {make} {model} {software}".strip())
    elif is_canva_software or is_canva_signature:
        is_canva_signature = True
        device_category = "canva"
        findings.append("Terverifikasi platform desain grafis Canva (canva.com).")
    elif is_screenshot_software:
        device_category = "screenshot"
        findings.append(f"Software '{software}' diketahui sebagai alat pengambil screenshot.")
    elif is_screenshot_filename:
        device_category = "screenshot"
        findings.append(f"Nama file '{filename}' mengandung kata kunci screenshot.")
    elif is_webcam:
        device_category = "webcam"
        findings.append(f"Terdeteksi kamera laptop / webcam: {make} {model} {software}".strip())
    elif "live_webcam" in filename.lower() or "webcam" in filename.lower():
        device_category = "webcam"
        findings.append("Citra dijepret langsung melalui antarmuka live webcam peramban.")
    elif is_phone:
        device_category = "smartphone"
        findings.append(f"Terdeteksi perangkat smartphone: {make} {model}".strip())
    elif is_camera:
        # Pengecualian jika Sony Xperia (hp)
        if "xperia" in full_cam_str:
            device_category = "smartphone"
            findings.append(f"Terdeteksi smartphone Sony Xperia: {model}")
        else:
            device_category = "dedicated_camera"
            findings.append(f"Terdeteksi kamera profesional/dedicated: {make} {model}")
            if lens_model:
                findings.append(f"Lensa terpasang: {lens_model}")

    if scan_preset:
        findings.append(f"Dimensi {pil_img.width}x{pil_img.height} px cocok dengan format scan baku: {scan_preset}.")
    if dpi_val:
        findings.append(f"Metadata resolusi cetak/pindai: {dpi_val} DPI.")
    if is_canva_filename:
        findings.append(f"Nama berkas '{filename}' mengindikasikan unduhan desain dari Canva.")
    if canva_preset and not has_exif and not is_scanner:
        findings.append(f"Dimensi {pil_img.width}x{pil_img.height} px cocok dengan template kanvas standar Canva: {canva_preset}.")

    # Crop factor & optical heuristics
    crop_factor = None
    if focal_length and focal_length_35mm and focal_length > 0:
        crop_factor = round(focal_length_35mm / focal_length, 1)
        if crop_factor >= 3.5:
            findings.append(f"Rasio sensor kecil (Crop Factor ~{crop_factor}x, FL fisik {focal_length}mm setara {focal_length_35mm}mm) khas modul kamera smartphone.")
            if device_category == "unknown":
                device_category = "smartphone"
        elif crop_factor <= 2.2 and crop_factor >= 0.8:
            findings.append(f"Rasio sensor besar (Crop Factor ~{crop_factor}x) khas sensor Full-Frame / APS-C / M43.")
            if device_category == "unknown":
                device_category = "dedicated_camera"

    if software:
        lower_soft = software.lower()
        if any(ai_s in lower_soft for ai_s in AI_SIGNATURES):
            ai_raw_matches.append(software)
            findings.append(f"Software pencipta mencatat: {software}")

    # Indikasi jika sama sekali tidak ada EXIF
    if not has_exif:
        findings.append("Tidak ditemukan metadata EXIF fisik kamera (kemungkinan dihapus media sosial atau digenerate langsung oleh AI).")

    return {
        "has_exif": has_exif,
        "make": make,
        "model": model,
        "lens_model": lens_model,
        "software": software,
        "focal_length": focal_length,
        "focal_length_35mm": focal_length_35mm,
        "crop_factor": crop_factor,
        "iso": iso,
        "f_number": f_number,
        "exposure_time": exposure_time,
        "date_time": date_time,
        "device_category": device_category,
        "is_screen_resolution": is_screen_resolution,
        "is_canva_signature": is_canva_signature,
        "is_canva_filename": is_canva_filename,
        "canva_preset_name": canva_preset,
        "is_canva_likely": is_canva_likely,
        "dpi": dpi_val,
        "is_scanner_device": is_scanner,
        "scan_preset_name": scan_preset,
        "ai_signatures_found": list(set(ai_raw_matches)),
        "findings": findings,
        "raw_summary": {k: v for k, v in list(exif_data.items())[:15]}
    }
